### PR TITLE
A Few Additions and Minor Updates

### PR DESCRIPTION
**Pull request by hasokeric**
I have added a few options.

Changelog:
- Added: requestType (GET, POST)
- Added: requestInterval (int)
- Added: timeout (int)
- Added: ifModified (true/false)
- Updated the readme accordingly
- Updated minified version (included also copyright notice)

### CODE REVIEW

**Comment by hasokeric** [comment]
Most of these additions will not work with a HTML5 eventsource because such as interval, ifmodified, requestType i doubt are yet supported however i have a strong belief that it will be supported as HTML5 is still just a draft in progress... Anyways i just wanted to share this with you because i still do jQuery Comet stuff and this helps me customize a bit.

**Comment by hasokeric** [comment]
It is also your choice wether to accept or deny this as i would understand it would break somewhat the 'eventsource' clone functionality... :) Keep up the good work.

**Comment by hasokeric** [comment]
I code my php on a framework and they dont really like the javascript ?20910291 to avoid caching so the POST method helps and my controller (in MVC) accepts of course both get and post... so thats mainly why i modified it... and also since most people will still be on older browsers for a while i can slow some of them down with the Requests :]

**Comment by rwaldron** [comment]
Cool, I'm thinking that maybe we should branch and apply your updates there?  That way they aren't overlooked or forgotten about and we can also continue building on them. What do you think?

**Comment by hasokeric** [comment]
Hello there buddy,

 I understand in the beginning i missed the point of this project to mimick exactly eventsource... i use your eventsource at our commercial web app... mainly for Comet (polling) which works very well :) i also use CodeIgniter and the GET with the ?2918921 (to avoid cache) doesnt work so i just modified it a bit... im pretty sure the eventsource (original) does not (or i hope it doesnt) append numbers...

Anyways it is up to you :o) i still have the fork and i will keep it of course .. keep up the good work and im not discouraged i am learning - pretty new to github and git overall :)

**Comment by hasokeric** [comment]
Perhaps what if we added another option that can override and have all browsers use the jQuery as event-source... sort of overrideEventSource: true; // now using jQuery on all browsers and ignoring html5 eventsource... ? thats where some of these options could be handy.. :P

**Comment by rwaldron** [comment]
So i've created a branch called "futures" and merged your changes in and pushed up.

**Pull request closed without merging**
